version: '3.8'

services:
  video-processor:
    build: .
    ports:
      - "5000:5000"
      - "8554:8554/udp"
    volumes:
      - ./processed_frames:/app/processed_frames
    environment:
      - FLASK_ENV=development
    restart: unless-stopped 